/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by '광수' at '17. 1. 26 오후 7:11' with Gradle 3.0
 *
 * @author 광수, @date 17. 1. 26 오후 7:11
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
